import {
  Accessibility,
  Activity,
  Ambulance,
  Apple,
  Bandage,
  Bike,
  Bird,
  Bone,
  BookOpen,
  Brain,
  Building2,
  Cat,
  Circle,
  CircleHelp,
  Clock,
  Cloud,
  Dog,
  Droplet,
  Dumbbell,
  FileText,
  Fish,
  Flower2,
  Footprints,
  Gavel,
  Globe,
  Handshake,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hospital,
  Info,
  Leaf,
  Lightbulb,
  MapPin,
  MessageCircle,
  Moon,
  Navigation,
  PawPrint,
  Phone,
  Pill,
  Plus,
  Rainbow,
  Scale,
  Search,
  ShieldCheck,
  Smile,
  Sparkles,
  Square,
  Stethoscope,
  Sun,
  Syringe,
  Thermometer,
  Triangle,
  Users,
} from "lucide-react"
import type { Doodle } from "./CategoryDoodles.types"

/**
 * Translucent drawings scattered over the category banner (desktop) and wallpaper (mobile), keyed by
 * category id. `left`/`top` in % of the banner, `size` in rem, `rotate` in degrees.
 * Each category mixes its own themed icons with a few plain shapes, on a different layout.
 */
export const CATEGORY_DOODLES: Record<string, Doodle[]> = {
  "primeros-auxilios": [
    { Icon: Plus, left: 30, top: 8, size: 2.5, rotate: 0 },
    { Icon: Bandage, left: 42, top: 55, size: 2.75, rotate: -20 },
    { Icon: Circle, left: 50, top: 12, size: 1.5, rotate: 0 },
    { Icon: HeartPulse, left: 56, top: 48, size: 2.5, rotate: 10 },
    { Icon: Triangle, left: 62, top: 6, size: 1.75, rotate: 15 },
    { Icon: Pill, left: 68, top: 62, size: 2, rotate: 35 },
    { Icon: Plus, left: 74, top: 20, size: 1.75, rotate: 0 },
    { Icon: Square, left: 80, top: 66, size: 1.5, rotate: 25 },
    { Icon: Stethoscope, left: 86, top: 10, size: 2.5, rotate: -10 },
    { Icon: Thermometer, left: 94, top: 50, size: 2.25, rotate: 20 },
  ],
  animales: [
    { Icon: PawPrint, left: 31, top: 58, size: 2.25, rotate: -15 },
    { Icon: Bone, left: 38, top: 10, size: 2.5, rotate: 30 },
    { Icon: Circle, left: 47, top: 44, size: 1.25, rotate: 0 },
    { Icon: Cat, left: 53, top: 8, size: 2.5, rotate: -8 },
    { Icon: PawPrint, left: 60, top: 60, size: 1.75, rotate: 20 },
    { Icon: Fish, left: 67, top: 24, size: 2.25, rotate: 12 },
    { Icon: Syringe, left: 74, top: 64, size: 2, rotate: -35 },
    { Icon: Dog, left: 81, top: 14, size: 2.75, rotate: 6 },
    { Icon: Triangle, left: 88, top: 58, size: 1.5, rotate: -20 },
    { Icon: Bird, left: 94, top: 22, size: 2, rotate: -12 },
  ],
  centros: [
    { Icon: Hospital, left: 32, top: 12, size: 2.5, rotate: -6 },
    { Icon: MapPin, left: 40, top: 58, size: 2.25, rotate: 10 },
    { Icon: Square, left: 49, top: 22, size: 1.25, rotate: 20 },
    { Icon: Ambulance, left: 55, top: 56, size: 2.75, rotate: -4 },
    { Icon: Clock, left: 63, top: 8, size: 2, rotate: 0 },
    { Icon: Plus, left: 70, top: 44, size: 1.75, rotate: 0 },
    { Icon: Phone, left: 76, top: 66, size: 2, rotate: -18 },
    { Icon: Building2, left: 82, top: 12, size: 2.5, rotate: 4 },
    { Icon: Circle, left: 89, top: 52, size: 1.5, rotate: 0 },
    { Icon: Navigation, left: 95, top: 18, size: 2, rotate: 25 },
  ],
  "salud-mental": [
    { Icon: Cloud, left: 30, top: 14, size: 2.75, rotate: 0 },
    { Icon: Heart, left: 39, top: 60, size: 2, rotate: -15 },
    { Icon: Sparkles, left: 48, top: 30, size: 1.75, rotate: 10 },
    { Icon: Brain, left: 55, top: 6, size: 2.5, rotate: -8 },
    { Icon: MessageCircle, left: 61, top: 56, size: 2.25, rotate: 8 },
    { Icon: Circle, left: 69, top: 18, size: 1.25, rotate: 0 },
    { Icon: Leaf, left: 74, top: 62, size: 2, rotate: 30 },
    { Icon: Sun, left: 81, top: 8, size: 2.5, rotate: 0 },
    { Icon: Moon, left: 88, top: 54, size: 2, rotate: -20 },
    { Icon: Flower2, left: 94, top: 16, size: 2.25, rotate: 12 },
  ],
  "salud-fisica": [
    { Icon: Activity, left: 31, top: 10, size: 2.5, rotate: 0 },
    { Icon: Apple, left: 39, top: 56, size: 2.25, rotate: -10 },
    { Icon: Triangle, left: 47, top: 18, size: 1.5, rotate: 30 },
    { Icon: Dumbbell, left: 54, top: 54, size: 2.5, rotate: -30 },
    { Icon: Droplet, left: 61, top: 10, size: 2, rotate: 10 },
    { Icon: Footprints, left: 68, top: 50, size: 2.25, rotate: 15 },
    { Icon: Plus, left: 75, top: 16, size: 1.75, rotate: 0 },
    { Icon: Bike, left: 81, top: 60, size: 2.5, rotate: -6 },
    { Icon: HeartPulse, left: 87, top: 8, size: 2.25, rotate: 8 },
    { Icon: Circle, left: 95, top: 48, size: 1.25, rotate: 0 },
  ],
  recursos: [
    { Icon: BookOpen, left: 30, top: 58, size: 2.5, rotate: -8 },
    { Icon: CircleHelp, left: 38, top: 10, size: 2.25, rotate: 10 },
    { Icon: Square, left: 47, top: 46, size: 1.25, rotate: 15 },
    { Icon: Scale, left: 53, top: 12, size: 2.5, rotate: -6 },
    { Icon: FileText, left: 60, top: 58, size: 2.25, rotate: 12 },
    { Icon: Lightbulb, left: 67, top: 16, size: 2, rotate: -15 },
    { Icon: Gavel, left: 74, top: 60, size: 2.25, rotate: -25 },
    { Icon: Search, left: 81, top: 10, size: 2, rotate: 0 },
    { Icon: Circle, left: 88, top: 48, size: 1.5, rotate: 0 },
    { Icon: Info, left: 94, top: 14, size: 2, rotate: 8 },
  ],
  esi: [
    { Icon: Heart, left: 31, top: 12, size: 2.25, rotate: -12 },
    { Icon: Users, left: 39, top: 56, size: 2.5, rotate: 4 },
    { Icon: Circle, left: 48, top: 22, size: 1.25, rotate: 0 },
    { Icon: Rainbow, left: 54, top: 54, size: 2.5, rotate: -8 },
    { Icon: ShieldCheck, left: 61, top: 8, size: 2.25, rotate: 10 },
    { Icon: MessageCircle, left: 68, top: 58, size: 2, rotate: -10 },
    { Icon: Sparkles, left: 74, top: 20, size: 1.75, rotate: 15 },
    { Icon: BookOpen, left: 81, top: 62, size: 2.25, rotate: 6 },
    { Icon: HeartHandshake, left: 87, top: 10, size: 2.5, rotate: -6 },
    { Icon: Triangle, left: 95, top: 52, size: 1.5, rotate: 20 },
  ],
  "sobre-auxiliar": [
    { Icon: Plus, left: 30, top: 54, size: 2.25, rotate: 0 },
    { Icon: Users, left: 37, top: 10, size: 2.5, rotate: -6 },
    { Icon: Circle, left: 46, top: 40, size: 1.25, rotate: 0 },
    { Icon: Globe, left: 52, top: 8, size: 2.5, rotate: 10 },
    { Icon: Heart, left: 59, top: 56, size: 2, rotate: 12 },
    { Icon: ShieldCheck, left: 66, top: 18, size: 2.25, rotate: -10 },
    { Icon: Accessibility, left: 73, top: 60, size: 2.25, rotate: 8 },
    { Icon: Square, left: 80, top: 14, size: 1.25, rotate: 25 },
    { Icon: Handshake, left: 86, top: 54, size: 2.5, rotate: -8 },
    { Icon: Smile, left: 94, top: 12, size: 2.25, rotate: 6 },
  ],
}

/** Mobile wallpaper: the same drawings on a staggered grid filling the whole (tall) area */
export const WALLPAPER_GRID = { columns: 3, rows: 5 }
